---
title: 'Ch. 2 Exercises: Credibility, Models, and Parameters'
author: "Thea Sukianto"
date: "January 19, 2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 2.1

Suppose we have a four-sided die from a board game. Ona tetrahedral die, each face is an equilateral triangle. When you roll the die, it lands withone face down and the other three faces visible as a three-sided pyramid. The faces are numbered 1-4, with the value of the bottom face printed (as clustered dots) at the bottom edges of all three visible faces. Denote the value of the bottom face as $x$. Consider the following three mathematical descriptions of the probabilities of $x$. Model A: $p(x)=\frac{1}{4}$. Model B: $p(x)=\frac{x}{10}$. Model C: $p(x)=\frac{12}{25x}$. For each model, determine the value of $p(x)$ for each value of $x$. Describe in words what kind of bias (or lack of bias) is expressed by each model.

| $x$ | $p(x)=\frac{1}{4}$ | $p(x)=\frac{x}{10}$ | $p(x)=\frac{12}{25x}$
|---| ------------------ | ------------------- | ------------------- |
| 1 | $\frac{1}{4}$ | $\frac{1}{10}$ | $\frac{12}{25}$ |
| 2 | $\frac{1}{4}$ | $\frac{1}{5}$ | $\frac{6}{25}$ |
| 3 | $\frac{1}{4}$ | $\frac{3}{10}$ | $\frac{4}{25}$ |
| 4 | $\frac{1}{4}$ | $\frac{2}{5}$ | $\frac{3}{25}$ |

### Discussion

Model A assumes equiprobable outcomes, i.e. the D4 is fair because each number has the same probability of being rolled. Models B and C express that the die is biased. In model B, the die is likely weighted so that rolling higher numbers is more probable. Conversely, in model C, the die is likely weighted so that rolling lower numbers is more probable.

## Exercise 2.2

Suppose we have the tetrahedral die introduced in the previous exercise, along with the three candidate models of the die’s probabilities. Suppose that initially, we are not sure what to believe about the die. On the one hand, the die might be fair, with each face landing with the same probability. On the other hand, the die might be biased, with the faces that have more dots landing down more often (because the dots are created by embedding heavy jewels in the die, so that the sides with more dots are more likely to land on the bottom). On yet another hand, the die might be biased such that more dots on a face make it less likely to land down (because maybe the dots are bouncy rubber or protrude from the surface). So, initially, our beliefs about the three models can be described as $p(A)=p(B)=p(C)=1/3$. Now we roll the die 100 times and find these results: #1’s=25, #2’s=25, #3’s=25, #4’s=25. Do these data change our beliefs about the models? Which model now seems most likely? Suppose when we rolled the die 100 times we found these results: #1’s=48, #2’s=24, #3’s=16, #4’s=12. Now which model seems most likely?

### Discussion

`#1’s = 25, #2’s = 25, #3’s = 25, #4’s = 25.`

Yes, these data change our beliefs about the models - in this case, each outcome occurs with the same frequency, so the equiprobable model (A) seems most likely.

`#1’s = 48, #2’s = 24, #3’s = 16, #4’s = 12.`

These data point toward lower rolls occuring more often, so the model where the probability of rolling $x$ is inversely proportional to $x$ (C) seems most likely.