---
title: "Bayesian Estimation of Daily Precipitation Probabilities in Idaho"
author: "Thea Sukianto"
date: "2/9/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo = FALSE, message = FALSE}
library(googlesheets4)
library(googledrive)
library(tidyverse)
library(zoo)
library(HDInterval)
library(rgdal)
library(maps)
library(tmap)
library(gstat)
library(sp)
library(raster)
```


```{r}
generate_posterior <- function(loc, window_size) {

  loc <- loc %>% 
    dplyr::mutate(if_precip = ifelse(precip_daily > 0 & !is.na(precip_daily), 1, 0),
                  window_sum = zoo::rollapply(if_precip, window_size, sum, fill = NA))
  
  loc$post_a <- NA # posterior alpha
  loc$post_b <- NA # posterior beta
  loc$post_avg <- NA # posterior mean
  loc$hdi_low <- NA
  loc$hdi_high <- NA
  
  
  loc$post_a[window_size/2] <- 1 # set first prior alpha to 1
  loc$post_b[window_size/2] <- 1 # set first prior beta to 1
    
  i <- (window_size/2)+1
  while(!is.na(loc$window_sum[i])) {
    loc$post_a[i] <- loc$window_sum[i] + loc$post_a[i-1]
    loc$post_b[i] <- window_size - loc$window_sum[i] + loc$post_b[i-1]
    loc$post_avg[i] <- (loc$window_sum[i] + loc$post_a[i-1])/(window_size + loc$post_a[i-1] + loc$post_b[i-1])
    
    loc$hdi_low <- hdi(qbeta(0.95, loc$post_a[i], loc$post_b[i]))[1]
    loc$hdi_high <- hdi(qbeta(0.95, loc$post_a[i], loc$post_b[i]))[2]
      
    i <- i + 1
  }
  return(loc)
}
```

```{r}
hdi_of_icdf <- function(name, width = .95, tol = 1e-8, ... ) {
  
  # (Function by Solomon Kurz)
  # Arguments:
  #   `name` is R's name for the inverse cumulative density function
  #   of the distribution.
  #   `width` is the desired mass of the HDI region.
  #   `tol` is passed to R's optimize function.
  # Return value:
  #   Highest density iterval (HDI) limits in a vector.
  # Example of use: For determining HDI of a beta(30, 12) distribution, type
  #   `hdi_of_icdf(qbeta, shape1 = 30, shape2 = 12)`
  #   Notice that the parameters of the `name` must be explicitly stated;
  #   e.g., `hdi_of_icdf(qbeta, 30, 12)` does not work.
  # Adapted and corrected from Greg Snow's TeachingDemos package.
  
  incredible_mass <- 1.0 - width
  interval_width <- function(low_tail_prob, name, width, ...) {
    name(width + low_tail_prob, ...) - name(low_tail_prob, ...)
  }
  
  opt_info <- optimize(interval_width, c(0, incredible_mass), 
                       name = name, width = width, 
                       tol = tol, ...)
  
  hdi_lower_tail_prob <- opt_info$minimum
  
  return(c(name(hdi_lower_tail_prob, ...),
           name(width + hdi_lower_tail_prob, ...)))
  
}
```



```{r}
gid_locations <- "1KCS7Xx2gt8sZDnWY2XSG6NKsZ_3H1QgC"
gid_parent <- "15H_C_7PPtwULzhJ45LPdIz7d2dcXARPu"
data_files <- drive_ls(as_id(gid_parent), pattern = "csv")
```


```{r, message = FALSE}
posterior_probs <- data.frame()

for(i in 1:nrow(data_files)) {
  
  data_raw <- read.csv(drive_download(as_id(data_files$id[1]))$local_path)

  loc <- data_raw %>% 
    dplyr::rename(precip = Accumulated.Precipitation) %>% 
    dplyr::mutate(precip_daily = precip - lag(precip),
                  precip_daily = ifelse(precip_daily < 0, NA, precip_daily))
  
  print(paste("Processing", i, "out of", nrow(data_files), loc$Station.Name[1]))
  
  print("Generating posterior probabilities")
  loc <- generate_posterior(loc, 10)
  
  posterior_probs <- posterior_probs %>% rbind(loc[nrow(loc)-5,])
}
```

```{r}
coords <- posterior_probs %>% select(Longitude, Latitude)
post_precip <- posterior_probs %>% select(post_avg)
pts <- SpatialPointsDataFrame(coords, post_precip)
idaho <- SpatialPolygons(list(Polygons(list(map_data("state") %>% filter(region == "idaho") %>% select(long, lat) %>% Polygon()), "Idaho")), proj4string = CRS("+proj=longlat +datum=WGS84"))

pts@bbox <- idaho@bbox

# From "Intro to GIS and Spatial Analysis" by Manuel Gimond: https://mgimond.github.io/Spatial/interpolation-in-r.html

# Create an empty grid where n is the total number of cells
grd              <- as.data.frame(spsample(pts, "regular", n=50000))
names(grd)       <- c("X", "Y")
coordinates(grd) <- c("X", "Y")
gridded(grd)     <- TRUE  # Create SpatialPixel object
fullgrid(grd)    <- TRUE  # Create SpatialGrid object

proj4string(pts) <- proj4string(pts) 
proj4string(grd) <- proj4string(pts)

# Interpolate the grid cells using a power value of 2 (idp=2.0)
pts.idw <- gstat::idw(post_avg ~ 1, pts, newdata=grd, idp=2.0)

r       <- raster(pts.idw)
r.m     <- mask(r, idaho)

tm_shape(r.m) + 
  tm_raster(n=10,palette = "RdBu",
            title="Precipitation Probability") + 
  tm_shape(pts) + tm_dots(size=0.2) +
  tm_legend(legend.outside=TRUE)
```
